import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-6 border-b flex justify-between bg-blue-500">
          <Link href={'/'}>Blog-app</Link>
          <Link href={'/post'}>Add New</Link>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
